package generic

// Code generated by go generate; DO NOT EDIT.

import (
	"github.com/mlange-42/arche/ecs"
)

//////////////////////////////////////////////////////////////////////////

// Map1 is a helper for mapping one components.
//
// # Example
//
//	world := ecs.NewWorld()
//
//	mapper := NewMap1[A](&world)
//
//	entity := mapper.NewEntity()
//	a := mapper.Get(entity)
type Map1[A any] struct {
	world  *ecs.World
	mask   ecs.Mask
	target int8
	ids    []ecs.ID
	id0    ecs.ID
}

// NewMap1 creates a new Map1 object.
//
// The optional argument can be used to set an [ecs.Relation] component type.
func NewMap1[A any](w *ecs.World, relation ...Comp) Map1[A] {
	m := Map1[A]{
		world: w,
		id0:   ecs.ComponentID[A](w),
	}
	m.ids = []ecs.ID{m.id0}
	m.mask = ecs.All(m.ids...)
	m.target = -1
	if len(relation) > 0 {
		m.target = int8(ecs.TypeID(w, relation[0]))
	}
	return m
}

// Get all the Map1's components for the given entity.
//
// See [Map1.GetUnchecked] for an optimized version for static entities.
// See also [ecs.World.Get].
func (m *Map1[A]) Get(entity ecs.Entity) *A {
	return (*A)(m.world.Get(entity, m.id0))
}

// GetUnchecked all the Map1's components for the given entity.
//
// GetUnchecked is an optimized version of [Map1.Get],
// for cases where entities are static or checked with [ecs.World.Alive] in user code.
//
// See also [ecs.World.GetUnchecked].
func (m *Map1[A]) GetUnchecked(entity ecs.Entity) *A {
	return (*A)(m.world.GetUnchecked(entity, m.id0))
}

// New creates a new [ecs.Entity] with the Map1's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map1's [ecs.Relation].
//
// See also [ecs.World.NewEntity].
func (m *Map1[A]) New(target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntity(m.ids...)
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).New(target[0])
}

// NewBatch creates entities with the Map1's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map1's [ecs.Relation].
//
// See also [Map1.NewQuery] and [ecs.Batch.NewBatch].
func (m *Map1[A]) NewBatch(count int, target ...ecs.Entity) {
	if len(target) == 0 {
		ecs.NewBuilder(m.world, m.ids...).NewBatch(count)
		return
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewBatch(count, target[0])
}

// NewQuery creates entities with the Map1's components.
// It returns a [Query1] over the new entities.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map1's [ecs.Relation].
//
// Listener notification is delayed until the query is closed of fully iterated.
//
// See also [Map1.NewBatch] and [ecs.Builder.NewQuery].
func (m *Map1[A]) NewQuery(count int, target ...ecs.Entity) Query1[A] {
	var query ecs.Query

	if len(target) == 0 {
		query = ecs.NewBuilder(m.world, m.ids...).NewQuery(count)
	} else {
		if m.target < 0 {
			panic("map has no relation defined")
		}
		query = ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewQuery(count, target[0])
	}

	return Query1[A]{
		Query: query,
		id0:   m.id0,
	}
}

// NewWith creates a new [ecs.Entity] with the Map1's components, using the supplied values.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map1's [ecs.Relation].
//
// See also [ecs.NewBuilderWith].
func (m *Map1[A]) NewWith(a *A, target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntityWith(ecs.Component{ID: m.id0, Comp: a})
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilderWith(m.world, ecs.Component{ID: m.id0, Comp: a}).WithRelation(uint8(m.target)).New(target[0])
}

// Add the Map1's components to the given entity.
//
// See also [ecs.World.Add].
func (m *Map1[A]) Add(entity ecs.Entity) {
	m.world.Add(entity, m.ids...)
}

// Assign the Map1's components to the given entity, using the supplied values.
//
// See also [ecs.World.Assign].
func (m *Map1[A]) Assign(entity ecs.Entity, a *A) {
	m.world.Assign(entity,
		ecs.Component{ID: m.id0, Comp: a},
	)
}

// Remove the Map1's components from the given entity.
//
// See also [ecs.World.Remove].
func (m *Map1[A]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}

// RemoveEntities removes all entities from the world that match the Map1's components.
//
// The argument determines whether to match the components exactly (i.e. no other components are allowed),
// or to use a simple filter that does not restrict further components.
//
// Returns the number of removed entities.
//
// See also [ecs.World.NewEntityWith].
func (m *Map1[A]) RemoveEntities(exclusive bool) int {
	if exclusive {
		filter := m.mask.Exclusive()
		return m.world.Batch().RemoveEntities(&filter)
	}
	return m.world.Batch().RemoveEntities(m.mask)
}

//////////////////////////////////////////////////////////////////////////

// Map2 is a helper for mapping two components.
//
// # Example
//
//	world := ecs.NewWorld()
//
//	mapper := NewMap2[A, B](&world)
//
//	entity := mapper.NewEntity()
//	a, b := mapper.Get(entity)
type Map2[A any, B any] struct {
	world  *ecs.World
	mask   ecs.Mask
	target int8
	ids    []ecs.ID
	id0    ecs.ID
	id1    ecs.ID
}

// NewMap2 creates a new Map2 object.
//
// The optional argument can be used to set an [ecs.Relation] component type.
func NewMap2[A any, B any](w *ecs.World, relation ...Comp) Map2[A, B] {
	m := Map2[A, B]{
		world: w,
		id0:   ecs.ComponentID[A](w),
		id1:   ecs.ComponentID[B](w),
	}
	m.ids = []ecs.ID{m.id0, m.id1}
	m.mask = ecs.All(m.ids...)
	m.target = -1
	if len(relation) > 0 {
		m.target = int8(ecs.TypeID(w, relation[0]))
	}
	return m
}

// Get all the Map2's components for the given entity.
//
// See [Map2.GetUnchecked] for an optimized version for static entities.
// See also [ecs.World.Get].
func (m *Map2[A, B]) Get(entity ecs.Entity) (*A, *B) {
	return (*A)(m.world.Get(entity, m.id0)),
		(*B)(m.world.GetUnchecked(entity, m.id1))
}

// GetUnchecked all the Map2's components for the given entity.
//
// GetUnchecked is an optimized version of [Map2.Get],
// for cases where entities are static or checked with [ecs.World.Alive] in user code.
//
// See also [ecs.World.GetUnchecked].
func (m *Map2[A, B]) GetUnchecked(entity ecs.Entity) (*A, *B) {
	return (*A)(m.world.GetUnchecked(entity, m.id0)),
		(*B)(m.world.GetUnchecked(entity, m.id1))
}

// New creates a new [ecs.Entity] with the Map2's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map2's [ecs.Relation].
//
// See also [ecs.World.NewEntity].
func (m *Map2[A, B]) New(target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntity(m.ids...)
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).New(target[0])
}

// NewBatch creates entities with the Map2's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map2's [ecs.Relation].
//
// See also [Map2.NewQuery] and [ecs.Batch.NewBatch].
func (m *Map2[A, B]) NewBatch(count int, target ...ecs.Entity) {
	if len(target) == 0 {
		ecs.NewBuilder(m.world, m.ids...).NewBatch(count)
		return
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewBatch(count, target[0])
}

// NewQuery creates entities with the Map2's components.
// It returns a [Query2] over the new entities.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map2's [ecs.Relation].
//
// Listener notification is delayed until the query is closed of fully iterated.
//
// See also [Map2.NewBatch] and [ecs.Builder.NewQuery].
func (m *Map2[A, B]) NewQuery(count int, target ...ecs.Entity) Query2[A, B] {
	var query ecs.Query

	if len(target) == 0 {
		query = ecs.NewBuilder(m.world, m.ids...).NewQuery(count)
	} else {
		if m.target < 0 {
			panic("map has no relation defined")
		}
		query = ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewQuery(count, target[0])
	}

	return Query2[A, B]{
		Query: query,
		id0:   m.id0,
		id1:   m.id1,
	}
}

// NewWith creates a new [ecs.Entity] with the Map2's components, using the supplied values.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map2's [ecs.Relation].
//
// See also [ecs.NewBuilderWith].
func (m *Map2[A, B]) NewWith(a *A, b *B, target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntityWith(ecs.Component{ID: m.id0, Comp: a},
			ecs.Component{ID: m.id1, Comp: b},
		)
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilderWith(m.world, ecs.Component{ID: m.id0, Comp: a},
		ecs.Component{ID: m.id1, Comp: b},
	).WithRelation(uint8(m.target)).New(target[0])
}

// Add the Map2's components to the given entity.
//
// See also [ecs.World.Add].
func (m *Map2[A, B]) Add(entity ecs.Entity) {
	m.world.Add(entity, m.ids...)
}

// Assign the Map2's components to the given entity, using the supplied values.
//
// See also [ecs.World.Assign].
func (m *Map2[A, B]) Assign(entity ecs.Entity, a *A, b *B) {
	m.world.Assign(entity,
		ecs.Component{ID: m.id0, Comp: a},
		ecs.Component{ID: m.id1, Comp: b},
	)
}

// Remove the Map2's components from the given entity.
//
// See also [ecs.World.Remove].
func (m *Map2[A, B]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}

// RemoveEntities removes all entities from the world that match the Map2's components.
//
// The argument determines whether to match the components exactly (i.e. no other components are allowed),
// or to use a simple filter that does not restrict further components.
//
// Returns the number of removed entities.
//
// See also [ecs.World.NewEntityWith].
func (m *Map2[A, B]) RemoveEntities(exclusive bool) int {
	if exclusive {
		filter := m.mask.Exclusive()
		return m.world.Batch().RemoveEntities(&filter)
	}
	return m.world.Batch().RemoveEntities(m.mask)
}

//////////////////////////////////////////////////////////////////////////

// Map3 is a helper for mapping three components.
//
// # Example
//
//	world := ecs.NewWorld()
//
//	mapper := NewMap3[A, B, C](&world)
//
//	entity := mapper.NewEntity()
//	a, b, c := mapper.Get(entity)
type Map3[A any, B any, C any] struct {
	world  *ecs.World
	mask   ecs.Mask
	target int8
	ids    []ecs.ID
	id0    ecs.ID
	id1    ecs.ID
	id2    ecs.ID
}

// NewMap3 creates a new Map3 object.
//
// The optional argument can be used to set an [ecs.Relation] component type.
func NewMap3[A any, B any, C any](w *ecs.World, relation ...Comp) Map3[A, B, C] {
	m := Map3[A, B, C]{
		world: w,
		id0:   ecs.ComponentID[A](w),
		id1:   ecs.ComponentID[B](w),
		id2:   ecs.ComponentID[C](w),
	}
	m.ids = []ecs.ID{m.id0, m.id1, m.id2}
	m.mask = ecs.All(m.ids...)
	m.target = -1
	if len(relation) > 0 {
		m.target = int8(ecs.TypeID(w, relation[0]))
	}
	return m
}

// Get all the Map3's components for the given entity.
//
// See [Map3.GetUnchecked] for an optimized version for static entities.
// See also [ecs.World.Get].
func (m *Map3[A, B, C]) Get(entity ecs.Entity) (*A, *B, *C) {
	return (*A)(m.world.Get(entity, m.id0)),
		(*B)(m.world.GetUnchecked(entity, m.id1)),
		(*C)(m.world.GetUnchecked(entity, m.id2))
}

// GetUnchecked all the Map3's components for the given entity.
//
// GetUnchecked is an optimized version of [Map3.Get],
// for cases where entities are static or checked with [ecs.World.Alive] in user code.
//
// See also [ecs.World.GetUnchecked].
func (m *Map3[A, B, C]) GetUnchecked(entity ecs.Entity) (*A, *B, *C) {
	return (*A)(m.world.GetUnchecked(entity, m.id0)),
		(*B)(m.world.GetUnchecked(entity, m.id1)),
		(*C)(m.world.GetUnchecked(entity, m.id2))
}

// New creates a new [ecs.Entity] with the Map3's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map3's [ecs.Relation].
//
// See also [ecs.World.NewEntity].
func (m *Map3[A, B, C]) New(target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntity(m.ids...)
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).New(target[0])
}

// NewBatch creates entities with the Map3's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map3's [ecs.Relation].
//
// See also [Map3.NewQuery] and [ecs.Batch.NewBatch].
func (m *Map3[A, B, C]) NewBatch(count int, target ...ecs.Entity) {
	if len(target) == 0 {
		ecs.NewBuilder(m.world, m.ids...).NewBatch(count)
		return
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewBatch(count, target[0])
}

// NewQuery creates entities with the Map3's components.
// It returns a [Query3] over the new entities.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map3's [ecs.Relation].
//
// Listener notification is delayed until the query is closed of fully iterated.
//
// See also [Map3.NewBatch] and [ecs.Builder.NewQuery].
func (m *Map3[A, B, C]) NewQuery(count int, target ...ecs.Entity) Query3[A, B, C] {
	var query ecs.Query

	if len(target) == 0 {
		query = ecs.NewBuilder(m.world, m.ids...).NewQuery(count)
	} else {
		if m.target < 0 {
			panic("map has no relation defined")
		}
		query = ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewQuery(count, target[0])
	}

	return Query3[A, B, C]{
		Query: query,
		id0:   m.id0,
		id1:   m.id1,
		id2:   m.id2,
	}
}

// NewWith creates a new [ecs.Entity] with the Map3's components, using the supplied values.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map3's [ecs.Relation].
//
// See also [ecs.NewBuilderWith].
func (m *Map3[A, B, C]) NewWith(a *A, b *B, c *C, target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntityWith(ecs.Component{ID: m.id0, Comp: a},
			ecs.Component{ID: m.id1, Comp: b},
			ecs.Component{ID: m.id2, Comp: c},
		)
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilderWith(m.world, ecs.Component{ID: m.id0, Comp: a},
		ecs.Component{ID: m.id1, Comp: b},
		ecs.Component{ID: m.id2, Comp: c},
	).WithRelation(uint8(m.target)).New(target[0])
}

// Add the Map3's components to the given entity.
//
// See also [ecs.World.Add].
func (m *Map3[A, B, C]) Add(entity ecs.Entity) {
	m.world.Add(entity, m.ids...)
}

// Assign the Map3's components to the given entity, using the supplied values.
//
// See also [ecs.World.Assign].
func (m *Map3[A, B, C]) Assign(entity ecs.Entity, a *A, b *B, c *C) {
	m.world.Assign(entity,
		ecs.Component{ID: m.id0, Comp: a},
		ecs.Component{ID: m.id1, Comp: b},
		ecs.Component{ID: m.id2, Comp: c},
	)
}

// Remove the Map3's components from the given entity.
//
// See also [ecs.World.Remove].
func (m *Map3[A, B, C]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}

// RemoveEntities removes all entities from the world that match the Map3's components.
//
// The argument determines whether to match the components exactly (i.e. no other components are allowed),
// or to use a simple filter that does not restrict further components.
//
// Returns the number of removed entities.
//
// See also [ecs.World.NewEntityWith].
func (m *Map3[A, B, C]) RemoveEntities(exclusive bool) int {
	if exclusive {
		filter := m.mask.Exclusive()
		return m.world.Batch().RemoveEntities(&filter)
	}
	return m.world.Batch().RemoveEntities(m.mask)
}

//////////////////////////////////////////////////////////////////////////

// Map4 is a helper for mapping four components.
//
// # Example
//
//	world := ecs.NewWorld()
//
//	mapper := NewMap4[A, B, C, D](&world)
//
//	entity := mapper.NewEntity()
//	a, b, c, d := mapper.Get(entity)
type Map4[A any, B any, C any, D any] struct {
	world  *ecs.World
	mask   ecs.Mask
	target int8
	ids    []ecs.ID
	id0    ecs.ID
	id1    ecs.ID
	id2    ecs.ID
	id3    ecs.ID
}

// NewMap4 creates a new Map4 object.
//
// The optional argument can be used to set an [ecs.Relation] component type.
func NewMap4[A any, B any, C any, D any](w *ecs.World, relation ...Comp) Map4[A, B, C, D] {
	m := Map4[A, B, C, D]{
		world: w,
		id0:   ecs.ComponentID[A](w),
		id1:   ecs.ComponentID[B](w),
		id2:   ecs.ComponentID[C](w),
		id3:   ecs.ComponentID[D](w),
	}
	m.ids = []ecs.ID{m.id0, m.id1, m.id2, m.id3}
	m.mask = ecs.All(m.ids...)
	m.target = -1
	if len(relation) > 0 {
		m.target = int8(ecs.TypeID(w, relation[0]))
	}
	return m
}

// Get all the Map4's components for the given entity.
//
// See [Map4.GetUnchecked] for an optimized version for static entities.
// See also [ecs.World.Get].
func (m *Map4[A, B, C, D]) Get(entity ecs.Entity) (*A, *B, *C, *D) {
	return (*A)(m.world.Get(entity, m.id0)),
		(*B)(m.world.GetUnchecked(entity, m.id1)),
		(*C)(m.world.GetUnchecked(entity, m.id2)),
		(*D)(m.world.GetUnchecked(entity, m.id3))
}

// GetUnchecked all the Map4's components for the given entity.
//
// GetUnchecked is an optimized version of [Map4.Get],
// for cases where entities are static or checked with [ecs.World.Alive] in user code.
//
// See also [ecs.World.GetUnchecked].
func (m *Map4[A, B, C, D]) GetUnchecked(entity ecs.Entity) (*A, *B, *C, *D) {
	return (*A)(m.world.GetUnchecked(entity, m.id0)),
		(*B)(m.world.GetUnchecked(entity, m.id1)),
		(*C)(m.world.GetUnchecked(entity, m.id2)),
		(*D)(m.world.GetUnchecked(entity, m.id3))
}

// New creates a new [ecs.Entity] with the Map4's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map4's [ecs.Relation].
//
// See also [ecs.World.NewEntity].
func (m *Map4[A, B, C, D]) New(target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntity(m.ids...)
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).New(target[0])
}

// NewBatch creates entities with the Map4's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map4's [ecs.Relation].
//
// See also [Map4.NewQuery] and [ecs.Batch.NewBatch].
func (m *Map4[A, B, C, D]) NewBatch(count int, target ...ecs.Entity) {
	if len(target) == 0 {
		ecs.NewBuilder(m.world, m.ids...).NewBatch(count)
		return
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewBatch(count, target[0])
}

// NewQuery creates entities with the Map4's components.
// It returns a [Query4] over the new entities.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map4's [ecs.Relation].
//
// Listener notification is delayed until the query is closed of fully iterated.
//
// See also [Map4.NewBatch] and [ecs.Builder.NewQuery].
func (m *Map4[A, B, C, D]) NewQuery(count int, target ...ecs.Entity) Query4[A, B, C, D] {
	var query ecs.Query

	if len(target) == 0 {
		query = ecs.NewBuilder(m.world, m.ids...).NewQuery(count)
	} else {
		if m.target < 0 {
			panic("map has no relation defined")
		}
		query = ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewQuery(count, target[0])
	}

	return Query4[A, B, C, D]{
		Query: query,
		id0:   m.id0,
		id1:   m.id1,
		id2:   m.id2,
		id3:   m.id3,
	}
}

// NewWith creates a new [ecs.Entity] with the Map4's components, using the supplied values.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map4's [ecs.Relation].
//
// See also [ecs.NewBuilderWith].
func (m *Map4[A, B, C, D]) NewWith(a *A, b *B, c *C, d *D, target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntityWith(ecs.Component{ID: m.id0, Comp: a},
			ecs.Component{ID: m.id1, Comp: b},
			ecs.Component{ID: m.id2, Comp: c},
			ecs.Component{ID: m.id3, Comp: d},
		)
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilderWith(m.world, ecs.Component{ID: m.id0, Comp: a},
		ecs.Component{ID: m.id1, Comp: b},
		ecs.Component{ID: m.id2, Comp: c},
		ecs.Component{ID: m.id3, Comp: d},
	).WithRelation(uint8(m.target)).New(target[0])
}

// Add the Map4's components to the given entity.
//
// See also [ecs.World.Add].
func (m *Map4[A, B, C, D]) Add(entity ecs.Entity) {
	m.world.Add(entity, m.ids...)
}

// Assign the Map4's components to the given entity, using the supplied values.
//
// See also [ecs.World.Assign].
func (m *Map4[A, B, C, D]) Assign(entity ecs.Entity, a *A, b *B, c *C, d *D) {
	m.world.Assign(entity,
		ecs.Component{ID: m.id0, Comp: a},
		ecs.Component{ID: m.id1, Comp: b},
		ecs.Component{ID: m.id2, Comp: c},
		ecs.Component{ID: m.id3, Comp: d},
	)
}

// Remove the Map4's components from the given entity.
//
// See also [ecs.World.Remove].
func (m *Map4[A, B, C, D]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}

// RemoveEntities removes all entities from the world that match the Map4's components.
//
// The argument determines whether to match the components exactly (i.e. no other components are allowed),
// or to use a simple filter that does not restrict further components.
//
// Returns the number of removed entities.
//
// See also [ecs.World.NewEntityWith].
func (m *Map4[A, B, C, D]) RemoveEntities(exclusive bool) int {
	if exclusive {
		filter := m.mask.Exclusive()
		return m.world.Batch().RemoveEntities(&filter)
	}
	return m.world.Batch().RemoveEntities(m.mask)
}

//////////////////////////////////////////////////////////////////////////

// Map5 is a helper for mapping five components.
//
// # Example
//
//	world := ecs.NewWorld()
//
//	mapper := NewMap5[A, B, C, D, E](&world)
//
//	entity := mapper.NewEntity()
//	a, b, c, d, e := mapper.Get(entity)
type Map5[A any, B any, C any, D any, E any] struct {
	world  *ecs.World
	mask   ecs.Mask
	target int8
	ids    []ecs.ID
	id0    ecs.ID
	id1    ecs.ID
	id2    ecs.ID
	id3    ecs.ID
	id4    ecs.ID
}

// NewMap5 creates a new Map5 object.
//
// The optional argument can be used to set an [ecs.Relation] component type.
func NewMap5[A any, B any, C any, D any, E any](w *ecs.World, relation ...Comp) Map5[A, B, C, D, E] {
	m := Map5[A, B, C, D, E]{
		world: w,
		id0:   ecs.ComponentID[A](w),
		id1:   ecs.ComponentID[B](w),
		id2:   ecs.ComponentID[C](w),
		id3:   ecs.ComponentID[D](w),
		id4:   ecs.ComponentID[E](w),
	}
	m.ids = []ecs.ID{m.id0, m.id1, m.id2, m.id3, m.id4}
	m.mask = ecs.All(m.ids...)
	m.target = -1
	if len(relation) > 0 {
		m.target = int8(ecs.TypeID(w, relation[0]))
	}
	return m
}

// Get all the Map5's components for the given entity.
//
// See [Map5.GetUnchecked] for an optimized version for static entities.
// See also [ecs.World.Get].
func (m *Map5[A, B, C, D, E]) Get(entity ecs.Entity) (*A, *B, *C, *D, *E) {
	return (*A)(m.world.Get(entity, m.id0)),
		(*B)(m.world.GetUnchecked(entity, m.id1)),
		(*C)(m.world.GetUnchecked(entity, m.id2)),
		(*D)(m.world.GetUnchecked(entity, m.id3)),
		(*E)(m.world.GetUnchecked(entity, m.id4))
}

// GetUnchecked all the Map5's components for the given entity.
//
// GetUnchecked is an optimized version of [Map5.Get],
// for cases where entities are static or checked with [ecs.World.Alive] in user code.
//
// See also [ecs.World.GetUnchecked].
func (m *Map5[A, B, C, D, E]) GetUnchecked(entity ecs.Entity) (*A, *B, *C, *D, *E) {
	return (*A)(m.world.GetUnchecked(entity, m.id0)),
		(*B)(m.world.GetUnchecked(entity, m.id1)),
		(*C)(m.world.GetUnchecked(entity, m.id2)),
		(*D)(m.world.GetUnchecked(entity, m.id3)),
		(*E)(m.world.GetUnchecked(entity, m.id4))
}

// New creates a new [ecs.Entity] with the Map5's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map5's [ecs.Relation].
//
// See also [ecs.World.NewEntity].
func (m *Map5[A, B, C, D, E]) New(target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntity(m.ids...)
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).New(target[0])
}

// NewBatch creates entities with the Map5's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map5's [ecs.Relation].
//
// See also [Map5.NewQuery] and [ecs.Batch.NewBatch].
func (m *Map5[A, B, C, D, E]) NewBatch(count int, target ...ecs.Entity) {
	if len(target) == 0 {
		ecs.NewBuilder(m.world, m.ids...).NewBatch(count)
		return
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewBatch(count, target[0])
}

// NewQuery creates entities with the Map5's components.
// It returns a [Query5] over the new entities.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map5's [ecs.Relation].
//
// Listener notification is delayed until the query is closed of fully iterated.
//
// See also [Map5.NewBatch] and [ecs.Builder.NewQuery].
func (m *Map5[A, B, C, D, E]) NewQuery(count int, target ...ecs.Entity) Query5[A, B, C, D, E] {
	var query ecs.Query

	if len(target) == 0 {
		query = ecs.NewBuilder(m.world, m.ids...).NewQuery(count)
	} else {
		if m.target < 0 {
			panic("map has no relation defined")
		}
		query = ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewQuery(count, target[0])
	}

	return Query5[A, B, C, D, E]{
		Query: query,
		id0:   m.id0,
		id1:   m.id1,
		id2:   m.id2,
		id3:   m.id3,
		id4:   m.id4,
	}
}

// NewWith creates a new [ecs.Entity] with the Map5's components, using the supplied values.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map5's [ecs.Relation].
//
// See also [ecs.NewBuilderWith].
func (m *Map5[A, B, C, D, E]) NewWith(a *A, b *B, c *C, d *D, e *E, target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntityWith(ecs.Component{ID: m.id0, Comp: a},
			ecs.Component{ID: m.id1, Comp: b},
			ecs.Component{ID: m.id2, Comp: c},
			ecs.Component{ID: m.id3, Comp: d},
			ecs.Component{ID: m.id4, Comp: e},
		)
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilderWith(m.world, ecs.Component{ID: m.id0, Comp: a},
		ecs.Component{ID: m.id1, Comp: b},
		ecs.Component{ID: m.id2, Comp: c},
		ecs.Component{ID: m.id3, Comp: d},
		ecs.Component{ID: m.id4, Comp: e},
	).WithRelation(uint8(m.target)).New(target[0])
}

// Add the Map5's components to the given entity.
//
// See also [ecs.World.Add].
func (m *Map5[A, B, C, D, E]) Add(entity ecs.Entity) {
	m.world.Add(entity, m.ids...)
}

// Assign the Map5's components to the given entity, using the supplied values.
//
// See also [ecs.World.Assign].
func (m *Map5[A, B, C, D, E]) Assign(entity ecs.Entity, a *A, b *B, c *C, d *D, e *E) {
	m.world.Assign(entity,
		ecs.Component{ID: m.id0, Comp: a},
		ecs.Component{ID: m.id1, Comp: b},
		ecs.Component{ID: m.id2, Comp: c},
		ecs.Component{ID: m.id3, Comp: d},
		ecs.Component{ID: m.id4, Comp: e},
	)
}

// Remove the Map5's components from the given entity.
//
// See also [ecs.World.Remove].
func (m *Map5[A, B, C, D, E]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}

// RemoveEntities removes all entities from the world that match the Map5's components.
//
// The argument determines whether to match the components exactly (i.e. no other components are allowed),
// or to use a simple filter that does not restrict further components.
//
// Returns the number of removed entities.
//
// See also [ecs.World.NewEntityWith].
func (m *Map5[A, B, C, D, E]) RemoveEntities(exclusive bool) int {
	if exclusive {
		filter := m.mask.Exclusive()
		return m.world.Batch().RemoveEntities(&filter)
	}
	return m.world.Batch().RemoveEntities(m.mask)
}

//////////////////////////////////////////////////////////////////////////

// Map6 is a helper for mapping six components.
//
// # Example
//
//	world := ecs.NewWorld()
//
//	mapper := NewMap6[A, B, C, D, E, F](&world)
//
//	entity := mapper.NewEntity()
//	a, b, c, d, e, f := mapper.Get(entity)
type Map6[A any, B any, C any, D any, E any, F any] struct {
	world  *ecs.World
	mask   ecs.Mask
	target int8
	ids    []ecs.ID
	id0    ecs.ID
	id1    ecs.ID
	id2    ecs.ID
	id3    ecs.ID
	id4    ecs.ID
	id5    ecs.ID
}

// NewMap6 creates a new Map6 object.
//
// The optional argument can be used to set an [ecs.Relation] component type.
func NewMap6[A any, B any, C any, D any, E any, F any](w *ecs.World, relation ...Comp) Map6[A, B, C, D, E, F] {
	m := Map6[A, B, C, D, E, F]{
		world: w,
		id0:   ecs.ComponentID[A](w),
		id1:   ecs.ComponentID[B](w),
		id2:   ecs.ComponentID[C](w),
		id3:   ecs.ComponentID[D](w),
		id4:   ecs.ComponentID[E](w),
		id5:   ecs.ComponentID[F](w),
	}
	m.ids = []ecs.ID{m.id0, m.id1, m.id2, m.id3, m.id4, m.id5}
	m.mask = ecs.All(m.ids...)
	m.target = -1
	if len(relation) > 0 {
		m.target = int8(ecs.TypeID(w, relation[0]))
	}
	return m
}

// Get all the Map6's components for the given entity.
//
// See [Map6.GetUnchecked] for an optimized version for static entities.
// See also [ecs.World.Get].
func (m *Map6[A, B, C, D, E, F]) Get(entity ecs.Entity) (*A, *B, *C, *D, *E, *F) {
	return (*A)(m.world.Get(entity, m.id0)),
		(*B)(m.world.GetUnchecked(entity, m.id1)),
		(*C)(m.world.GetUnchecked(entity, m.id2)),
		(*D)(m.world.GetUnchecked(entity, m.id3)),
		(*E)(m.world.GetUnchecked(entity, m.id4)),
		(*F)(m.world.GetUnchecked(entity, m.id5))
}

// GetUnchecked all the Map6's components for the given entity.
//
// GetUnchecked is an optimized version of [Map6.Get],
// for cases where entities are static or checked with [ecs.World.Alive] in user code.
//
// See also [ecs.World.GetUnchecked].
func (m *Map6[A, B, C, D, E, F]) GetUnchecked(entity ecs.Entity) (*A, *B, *C, *D, *E, *F) {
	return (*A)(m.world.GetUnchecked(entity, m.id0)),
		(*B)(m.world.GetUnchecked(entity, m.id1)),
		(*C)(m.world.GetUnchecked(entity, m.id2)),
		(*D)(m.world.GetUnchecked(entity, m.id3)),
		(*E)(m.world.GetUnchecked(entity, m.id4)),
		(*F)(m.world.GetUnchecked(entity, m.id5))
}

// New creates a new [ecs.Entity] with the Map6's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map6's [ecs.Relation].
//
// See also [ecs.World.NewEntity].
func (m *Map6[A, B, C, D, E, F]) New(target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntity(m.ids...)
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).New(target[0])
}

// NewBatch creates entities with the Map6's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map6's [ecs.Relation].
//
// See also [Map6.NewQuery] and [ecs.Batch.NewBatch].
func (m *Map6[A, B, C, D, E, F]) NewBatch(count int, target ...ecs.Entity) {
	if len(target) == 0 {
		ecs.NewBuilder(m.world, m.ids...).NewBatch(count)
		return
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewBatch(count, target[0])
}

// NewQuery creates entities with the Map6's components.
// It returns a [Query6] over the new entities.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map6's [ecs.Relation].
//
// Listener notification is delayed until the query is closed of fully iterated.
//
// See also [Map6.NewBatch] and [ecs.Builder.NewQuery].
func (m *Map6[A, B, C, D, E, F]) NewQuery(count int, target ...ecs.Entity) Query6[A, B, C, D, E, F] {
	var query ecs.Query

	if len(target) == 0 {
		query = ecs.NewBuilder(m.world, m.ids...).NewQuery(count)
	} else {
		if m.target < 0 {
			panic("map has no relation defined")
		}
		query = ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewQuery(count, target[0])
	}

	return Query6[A, B, C, D, E, F]{
		Query: query,
		id0:   m.id0,
		id1:   m.id1,
		id2:   m.id2,
		id3:   m.id3,
		id4:   m.id4,
		id5:   m.id5,
	}
}

// NewWith creates a new [ecs.Entity] with the Map6's components, using the supplied values.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map6's [ecs.Relation].
//
// See also [ecs.NewBuilderWith].
func (m *Map6[A, B, C, D, E, F]) NewWith(a *A, b *B, c *C, d *D, e *E, f *F, target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntityWith(ecs.Component{ID: m.id0, Comp: a},
			ecs.Component{ID: m.id1, Comp: b},
			ecs.Component{ID: m.id2, Comp: c},
			ecs.Component{ID: m.id3, Comp: d},
			ecs.Component{ID: m.id4, Comp: e},
			ecs.Component{ID: m.id5, Comp: f},
		)
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilderWith(m.world, ecs.Component{ID: m.id0, Comp: a},
		ecs.Component{ID: m.id1, Comp: b},
		ecs.Component{ID: m.id2, Comp: c},
		ecs.Component{ID: m.id3, Comp: d},
		ecs.Component{ID: m.id4, Comp: e},
		ecs.Component{ID: m.id5, Comp: f},
	).WithRelation(uint8(m.target)).New(target[0])
}

// Add the Map6's components to the given entity.
//
// See also [ecs.World.Add].
func (m *Map6[A, B, C, D, E, F]) Add(entity ecs.Entity) {
	m.world.Add(entity, m.ids...)
}

// Assign the Map6's components to the given entity, using the supplied values.
//
// See also [ecs.World.Assign].
func (m *Map6[A, B, C, D, E, F]) Assign(entity ecs.Entity, a *A, b *B, c *C, d *D, e *E, f *F) {
	m.world.Assign(entity,
		ecs.Component{ID: m.id0, Comp: a},
		ecs.Component{ID: m.id1, Comp: b},
		ecs.Component{ID: m.id2, Comp: c},
		ecs.Component{ID: m.id3, Comp: d},
		ecs.Component{ID: m.id4, Comp: e},
		ecs.Component{ID: m.id5, Comp: f},
	)
}

// Remove the Map6's components from the given entity.
//
// See also [ecs.World.Remove].
func (m *Map6[A, B, C, D, E, F]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}

// RemoveEntities removes all entities from the world that match the Map6's components.
//
// The argument determines whether to match the components exactly (i.e. no other components are allowed),
// or to use a simple filter that does not restrict further components.
//
// Returns the number of removed entities.
//
// See also [ecs.World.NewEntityWith].
func (m *Map6[A, B, C, D, E, F]) RemoveEntities(exclusive bool) int {
	if exclusive {
		filter := m.mask.Exclusive()
		return m.world.Batch().RemoveEntities(&filter)
	}
	return m.world.Batch().RemoveEntities(m.mask)
}

//////////////////////////////////////////////////////////////////////////

// Map7 is a helper for mapping seven components.
//
// # Example
//
//	world := ecs.NewWorld()
//
//	mapper := NewMap7[A, B, C, D, E, F, G](&world)
//
//	entity := mapper.NewEntity()
//	a, b, c, d, e, f, g := mapper.Get(entity)
type Map7[A any, B any, C any, D any, E any, F any, G any] struct {
	world  *ecs.World
	mask   ecs.Mask
	target int8
	ids    []ecs.ID
	id0    ecs.ID
	id1    ecs.ID
	id2    ecs.ID
	id3    ecs.ID
	id4    ecs.ID
	id5    ecs.ID
	id6    ecs.ID
}

// NewMap7 creates a new Map7 object.
//
// The optional argument can be used to set an [ecs.Relation] component type.
func NewMap7[A any, B any, C any, D any, E any, F any, G any](w *ecs.World, relation ...Comp) Map7[A, B, C, D, E, F, G] {
	m := Map7[A, B, C, D, E, F, G]{
		world: w,
		id0:   ecs.ComponentID[A](w),
		id1:   ecs.ComponentID[B](w),
		id2:   ecs.ComponentID[C](w),
		id3:   ecs.ComponentID[D](w),
		id4:   ecs.ComponentID[E](w),
		id5:   ecs.ComponentID[F](w),
		id6:   ecs.ComponentID[G](w),
	}
	m.ids = []ecs.ID{m.id0, m.id1, m.id2, m.id3, m.id4, m.id5, m.id6}
	m.mask = ecs.All(m.ids...)
	m.target = -1
	if len(relation) > 0 {
		m.target = int8(ecs.TypeID(w, relation[0]))
	}
	return m
}

// Get all the Map7's components for the given entity.
//
// See [Map7.GetUnchecked] for an optimized version for static entities.
// See also [ecs.World.Get].
func (m *Map7[A, B, C, D, E, F, G]) Get(entity ecs.Entity) (*A, *B, *C, *D, *E, *F, *G) {
	return (*A)(m.world.Get(entity, m.id0)),
		(*B)(m.world.GetUnchecked(entity, m.id1)),
		(*C)(m.world.GetUnchecked(entity, m.id2)),
		(*D)(m.world.GetUnchecked(entity, m.id3)),
		(*E)(m.world.GetUnchecked(entity, m.id4)),
		(*F)(m.world.GetUnchecked(entity, m.id5)),
		(*G)(m.world.GetUnchecked(entity, m.id6))
}

// GetUnchecked all the Map7's components for the given entity.
//
// GetUnchecked is an optimized version of [Map7.Get],
// for cases where entities are static or checked with [ecs.World.Alive] in user code.
//
// See also [ecs.World.GetUnchecked].
func (m *Map7[A, B, C, D, E, F, G]) GetUnchecked(entity ecs.Entity) (*A, *B, *C, *D, *E, *F, *G) {
	return (*A)(m.world.GetUnchecked(entity, m.id0)),
		(*B)(m.world.GetUnchecked(entity, m.id1)),
		(*C)(m.world.GetUnchecked(entity, m.id2)),
		(*D)(m.world.GetUnchecked(entity, m.id3)),
		(*E)(m.world.GetUnchecked(entity, m.id4)),
		(*F)(m.world.GetUnchecked(entity, m.id5)),
		(*G)(m.world.GetUnchecked(entity, m.id6))
}

// New creates a new [ecs.Entity] with the Map7's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map7's [ecs.Relation].
//
// See also [ecs.World.NewEntity].
func (m *Map7[A, B, C, D, E, F, G]) New(target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntity(m.ids...)
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).New(target[0])
}

// NewBatch creates entities with the Map7's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map7's [ecs.Relation].
//
// See also [Map7.NewQuery] and [ecs.Batch.NewBatch].
func (m *Map7[A, B, C, D, E, F, G]) NewBatch(count int, target ...ecs.Entity) {
	if len(target) == 0 {
		ecs.NewBuilder(m.world, m.ids...).NewBatch(count)
		return
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewBatch(count, target[0])
}

// NewQuery creates entities with the Map7's components.
// It returns a [Query7] over the new entities.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map7's [ecs.Relation].
//
// Listener notification is delayed until the query is closed of fully iterated.
//
// See also [Map7.NewBatch] and [ecs.Builder.NewQuery].
func (m *Map7[A, B, C, D, E, F, G]) NewQuery(count int, target ...ecs.Entity) Query7[A, B, C, D, E, F, G] {
	var query ecs.Query

	if len(target) == 0 {
		query = ecs.NewBuilder(m.world, m.ids...).NewQuery(count)
	} else {
		if m.target < 0 {
			panic("map has no relation defined")
		}
		query = ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewQuery(count, target[0])
	}

	return Query7[A, B, C, D, E, F, G]{
		Query: query,
		id0:   m.id0,
		id1:   m.id1,
		id2:   m.id2,
		id3:   m.id3,
		id4:   m.id4,
		id5:   m.id5,
		id6:   m.id6,
	}
}

// NewWith creates a new [ecs.Entity] with the Map7's components, using the supplied values.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map7's [ecs.Relation].
//
// See also [ecs.NewBuilderWith].
func (m *Map7[A, B, C, D, E, F, G]) NewWith(a *A, b *B, c *C, d *D, e *E, f *F, g *G, target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntityWith(ecs.Component{ID: m.id0, Comp: a},
			ecs.Component{ID: m.id1, Comp: b},
			ecs.Component{ID: m.id2, Comp: c},
			ecs.Component{ID: m.id3, Comp: d},
			ecs.Component{ID: m.id4, Comp: e},
			ecs.Component{ID: m.id5, Comp: f},
			ecs.Component{ID: m.id6, Comp: g},
		)
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilderWith(m.world, ecs.Component{ID: m.id0, Comp: a},
		ecs.Component{ID: m.id1, Comp: b},
		ecs.Component{ID: m.id2, Comp: c},
		ecs.Component{ID: m.id3, Comp: d},
		ecs.Component{ID: m.id4, Comp: e},
		ecs.Component{ID: m.id5, Comp: f},
		ecs.Component{ID: m.id6, Comp: g},
	).WithRelation(uint8(m.target)).New(target[0])
}

// Add the Map7's components to the given entity.
//
// See also [ecs.World.Add].
func (m *Map7[A, B, C, D, E, F, G]) Add(entity ecs.Entity) {
	m.world.Add(entity, m.ids...)
}

// Assign the Map7's components to the given entity, using the supplied values.
//
// See also [ecs.World.Assign].
func (m *Map7[A, B, C, D, E, F, G]) Assign(entity ecs.Entity, a *A, b *B, c *C, d *D, e *E, f *F, g *G) {
	m.world.Assign(entity,
		ecs.Component{ID: m.id0, Comp: a},
		ecs.Component{ID: m.id1, Comp: b},
		ecs.Component{ID: m.id2, Comp: c},
		ecs.Component{ID: m.id3, Comp: d},
		ecs.Component{ID: m.id4, Comp: e},
		ecs.Component{ID: m.id5, Comp: f},
		ecs.Component{ID: m.id6, Comp: g},
	)
}

// Remove the Map7's components from the given entity.
//
// See also [ecs.World.Remove].
func (m *Map7[A, B, C, D, E, F, G]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}

// RemoveEntities removes all entities from the world that match the Map7's components.
//
// The argument determines whether to match the components exactly (i.e. no other components are allowed),
// or to use a simple filter that does not restrict further components.
//
// Returns the number of removed entities.
//
// See also [ecs.World.NewEntityWith].
func (m *Map7[A, B, C, D, E, F, G]) RemoveEntities(exclusive bool) int {
	if exclusive {
		filter := m.mask.Exclusive()
		return m.world.Batch().RemoveEntities(&filter)
	}
	return m.world.Batch().RemoveEntities(m.mask)
}

//////////////////////////////////////////////////////////////////////////

// Map8 is a helper for mapping eight components.
//
// # Example
//
//	world := ecs.NewWorld()
//
//	mapper := NewMap8[A, B, C, D, E, F, G, H](&world)
//
//	entity := mapper.NewEntity()
//	a, b, c, d, e, f, g, h := mapper.Get(entity)
type Map8[A any, B any, C any, D any, E any, F any, G any, H any] struct {
	world  *ecs.World
	mask   ecs.Mask
	target int8
	ids    []ecs.ID
	id0    ecs.ID
	id1    ecs.ID
	id2    ecs.ID
	id3    ecs.ID
	id4    ecs.ID
	id5    ecs.ID
	id6    ecs.ID
	id7    ecs.ID
}

// NewMap8 creates a new Map8 object.
//
// The optional argument can be used to set an [ecs.Relation] component type.
func NewMap8[A any, B any, C any, D any, E any, F any, G any, H any](w *ecs.World, relation ...Comp) Map8[A, B, C, D, E, F, G, H] {
	m := Map8[A, B, C, D, E, F, G, H]{
		world: w,
		id0:   ecs.ComponentID[A](w),
		id1:   ecs.ComponentID[B](w),
		id2:   ecs.ComponentID[C](w),
		id3:   ecs.ComponentID[D](w),
		id4:   ecs.ComponentID[E](w),
		id5:   ecs.ComponentID[F](w),
		id6:   ecs.ComponentID[G](w),
		id7:   ecs.ComponentID[H](w),
	}
	m.ids = []ecs.ID{m.id0, m.id1, m.id2, m.id3, m.id4, m.id5, m.id6, m.id7}
	m.mask = ecs.All(m.ids...)
	m.target = -1
	if len(relation) > 0 {
		m.target = int8(ecs.TypeID(w, relation[0]))
	}
	return m
}

// Get all the Map8's components for the given entity.
//
// See [Map8.GetUnchecked] for an optimized version for static entities.
// See also [ecs.World.Get].
func (m *Map8[A, B, C, D, E, F, G, H]) Get(entity ecs.Entity) (*A, *B, *C, *D, *E, *F, *G, *H) {
	return (*A)(m.world.Get(entity, m.id0)),
		(*B)(m.world.GetUnchecked(entity, m.id1)),
		(*C)(m.world.GetUnchecked(entity, m.id2)),
		(*D)(m.world.GetUnchecked(entity, m.id3)),
		(*E)(m.world.GetUnchecked(entity, m.id4)),
		(*F)(m.world.GetUnchecked(entity, m.id5)),
		(*G)(m.world.GetUnchecked(entity, m.id6)),
		(*H)(m.world.GetUnchecked(entity, m.id7))
}

// GetUnchecked all the Map8's components for the given entity.
//
// GetUnchecked is an optimized version of [Map8.Get],
// for cases where entities are static or checked with [ecs.World.Alive] in user code.
//
// See also [ecs.World.GetUnchecked].
func (m *Map8[A, B, C, D, E, F, G, H]) GetUnchecked(entity ecs.Entity) (*A, *B, *C, *D, *E, *F, *G, *H) {
	return (*A)(m.world.GetUnchecked(entity, m.id0)),
		(*B)(m.world.GetUnchecked(entity, m.id1)),
		(*C)(m.world.GetUnchecked(entity, m.id2)),
		(*D)(m.world.GetUnchecked(entity, m.id3)),
		(*E)(m.world.GetUnchecked(entity, m.id4)),
		(*F)(m.world.GetUnchecked(entity, m.id5)),
		(*G)(m.world.GetUnchecked(entity, m.id6)),
		(*H)(m.world.GetUnchecked(entity, m.id7))
}

// New creates a new [ecs.Entity] with the Map8's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map8's [ecs.Relation].
//
// See also [ecs.World.NewEntity].
func (m *Map8[A, B, C, D, E, F, G, H]) New(target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntity(m.ids...)
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).New(target[0])
}

// NewBatch creates entities with the Map8's components.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map8's [ecs.Relation].
//
// See also [Map8.NewQuery] and [ecs.Batch.NewBatch].
func (m *Map8[A, B, C, D, E, F, G, H]) NewBatch(count int, target ...ecs.Entity) {
	if len(target) == 0 {
		ecs.NewBuilder(m.world, m.ids...).NewBatch(count)
		return
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewBatch(count, target[0])
}

// NewQuery creates entities with the Map8's components.
// It returns a [Query8] over the new entities.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map8's [ecs.Relation].
//
// Listener notification is delayed until the query is closed of fully iterated.
//
// See also [Map8.NewBatch] and [ecs.Builder.NewQuery].
func (m *Map8[A, B, C, D, E, F, G, H]) NewQuery(count int, target ...ecs.Entity) Query8[A, B, C, D, E, F, G, H] {
	var query ecs.Query

	if len(target) == 0 {
		query = ecs.NewBuilder(m.world, m.ids...).NewQuery(count)
	} else {
		if m.target < 0 {
			panic("map has no relation defined")
		}
		query = ecs.NewBuilder(m.world, m.ids...).WithRelation(uint8(m.target)).NewQuery(count, target[0])
	}

	return Query8[A, B, C, D, E, F, G, H]{
		Query: query,
		id0:   m.id0,
		id1:   m.id1,
		id2:   m.id2,
		id3:   m.id3,
		id4:   m.id4,
		id5:   m.id5,
		id6:   m.id6,
		id7:   m.id7,
	}
}

// NewWith creates a new [ecs.Entity] with the Map8's components, using the supplied values.
//
// The optional argument can be used to set the target [ecs.Entity] for the Map8's [ecs.Relation].
//
// See also [ecs.NewBuilderWith].
func (m *Map8[A, B, C, D, E, F, G, H]) NewWith(a *A, b *B, c *C, d *D, e *E, f *F, g *G, h *H, target ...ecs.Entity) ecs.Entity {
	if len(target) == 0 {
		return m.world.NewEntityWith(ecs.Component{ID: m.id0, Comp: a},
			ecs.Component{ID: m.id1, Comp: b},
			ecs.Component{ID: m.id2, Comp: c},
			ecs.Component{ID: m.id3, Comp: d},
			ecs.Component{ID: m.id4, Comp: e},
			ecs.Component{ID: m.id5, Comp: f},
			ecs.Component{ID: m.id6, Comp: g},
			ecs.Component{ID: m.id7, Comp: h},
		)
	}
	if m.target < 0 {
		panic("map has no relation defined")
	}
	return ecs.NewBuilderWith(m.world, ecs.Component{ID: m.id0, Comp: a},
		ecs.Component{ID: m.id1, Comp: b},
		ecs.Component{ID: m.id2, Comp: c},
		ecs.Component{ID: m.id3, Comp: d},
		ecs.Component{ID: m.id4, Comp: e},
		ecs.Component{ID: m.id5, Comp: f},
		ecs.Component{ID: m.id6, Comp: g},
		ecs.Component{ID: m.id7, Comp: h},
	).WithRelation(uint8(m.target)).New(target[0])
}

// Add the Map8's components to the given entity.
//
// See also [ecs.World.Add].
func (m *Map8[A, B, C, D, E, F, G, H]) Add(entity ecs.Entity) {
	m.world.Add(entity, m.ids...)
}

// Assign the Map8's components to the given entity, using the supplied values.
//
// See also [ecs.World.Assign].
func (m *Map8[A, B, C, D, E, F, G, H]) Assign(entity ecs.Entity, a *A, b *B, c *C, d *D, e *E, f *F, g *G, h *H) {
	m.world.Assign(entity,
		ecs.Component{ID: m.id0, Comp: a},
		ecs.Component{ID: m.id1, Comp: b},
		ecs.Component{ID: m.id2, Comp: c},
		ecs.Component{ID: m.id3, Comp: d},
		ecs.Component{ID: m.id4, Comp: e},
		ecs.Component{ID: m.id5, Comp: f},
		ecs.Component{ID: m.id6, Comp: g},
		ecs.Component{ID: m.id7, Comp: h},
	)
}

// Remove the Map8's components from the given entity.
//
// See also [ecs.World.Remove].
func (m *Map8[A, B, C, D, E, F, G, H]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}

// RemoveEntities removes all entities from the world that match the Map8's components.
//
// The argument determines whether to match the components exactly (i.e. no other components are allowed),
// or to use a simple filter that does not restrict further components.
//
// Returns the number of removed entities.
//
// See also [ecs.World.NewEntityWith].
func (m *Map8[A, B, C, D, E, F, G, H]) RemoveEntities(exclusive bool) int {
	if exclusive {
		filter := m.mask.Exclusive()
		return m.world.Batch().RemoveEntities(&filter)
	}
	return m.world.Batch().RemoveEntities(m.mask)
}
