package generic

// Code generated by go generate; DO NOT EDIT.

import (
	"github.com/mlange-42/arche/ecs"
)

//////////////////////////////////////////////////////////////////////////

// Map1 is a helper for mapping one components.
type Map1[A any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMap1 creates a new Map1 object.
func NewMap1[A any](w *ecs.World) Map1[A] {
	return Map1[A]{
		ids:   []ecs.ID{ecs.ComponentID[A](w)},
		world: w,
	}
}

// Get all the Map1's components to the given entity.
//
// See also [ecs.World.Get].
func (m *Map1[A]) Get(entity ecs.Entity) *A {
	return (*A)(m.world.Get(entity, m.ids[0]))
}

//////////////////////////////////////////////////////////////////////////

// Map2 is a helper for mapping two components.
type Map2[A any, B any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMap2 creates a new Map2 object.
func NewMap2[A any, B any](w *ecs.World) Map2[A, B] {
	return Map2[A, B]{
		ids:   []ecs.ID{ecs.ComponentID[A](w), ecs.ComponentID[B](w)},
		world: w,
	}
}

// Get all the Map2's components to the given entity.
//
// See also [ecs.World.Get].
func (m *Map2[A, B]) Get(entity ecs.Entity) (*A, *B) {
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1]))
}

//////////////////////////////////////////////////////////////////////////

// Map3 is a helper for mapping three components.
type Map3[A any, B any, C any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMap3 creates a new Map3 object.
func NewMap3[A any, B any, C any](w *ecs.World) Map3[A, B, C] {
	return Map3[A, B, C]{
		ids:   []ecs.ID{ecs.ComponentID[A](w), ecs.ComponentID[B](w), ecs.ComponentID[C](w)},
		world: w,
	}
}

// Get all the Map3's components to the given entity.
//
// See also [ecs.World.Get].
func (m *Map3[A, B, C]) Get(entity ecs.Entity) (*A, *B, *C) {
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2]))
}

//////////////////////////////////////////////////////////////////////////

// Map4 is a helper for mapping four components.
type Map4[A any, B any, C any, D any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMap4 creates a new Map4 object.
func NewMap4[A any, B any, C any, D any](w *ecs.World) Map4[A, B, C, D] {
	return Map4[A, B, C, D]{
		ids:   []ecs.ID{ecs.ComponentID[A](w), ecs.ComponentID[B](w), ecs.ComponentID[C](w), ecs.ComponentID[D](w)},
		world: w,
	}
}

// Get all the Map4's components to the given entity.
//
// See also [ecs.World.Get].
func (m *Map4[A, B, C, D]) Get(entity ecs.Entity) (*A, *B, *C, *D) {
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3]))
}

//////////////////////////////////////////////////////////////////////////

// Map5 is a helper for mapping five components.
type Map5[A any, B any, C any, D any, E any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMap5 creates a new Map5 object.
func NewMap5[A any, B any, C any, D any, E any](w *ecs.World) Map5[A, B, C, D, E] {
	return Map5[A, B, C, D, E]{
		ids:   []ecs.ID{ecs.ComponentID[A](w), ecs.ComponentID[B](w), ecs.ComponentID[C](w), ecs.ComponentID[D](w), ecs.ComponentID[E](w)},
		world: w,
	}
}

// Get all the Map5's components to the given entity.
//
// See also [ecs.World.Get].
func (m *Map5[A, B, C, D, E]) Get(entity ecs.Entity) (*A, *B, *C, *D, *E) {
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4]))
}

//////////////////////////////////////////////////////////////////////////

// Map6 is a helper for mapping six components.
type Map6[A any, B any, C any, D any, E any, F any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMap6 creates a new Map6 object.
func NewMap6[A any, B any, C any, D any, E any, F any](w *ecs.World) Map6[A, B, C, D, E, F] {
	return Map6[A, B, C, D, E, F]{
		ids:   []ecs.ID{ecs.ComponentID[A](w), ecs.ComponentID[B](w), ecs.ComponentID[C](w), ecs.ComponentID[D](w), ecs.ComponentID[E](w), ecs.ComponentID[F](w)},
		world: w,
	}
}

// Get all the Map6's components to the given entity.
//
// See also [ecs.World.Get].
func (m *Map6[A, B, C, D, E, F]) Get(entity ecs.Entity) (*A, *B, *C, *D, *E, *F) {
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4])), (*F)(m.world.Get(entity, m.ids[5]))
}

//////////////////////////////////////////////////////////////////////////

// Map7 is a helper for mapping seven components.
type Map7[A any, B any, C any, D any, E any, F any, G any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMap7 creates a new Map7 object.
func NewMap7[A any, B any, C any, D any, E any, F any, G any](w *ecs.World) Map7[A, B, C, D, E, F, G] {
	return Map7[A, B, C, D, E, F, G]{
		ids:   []ecs.ID{ecs.ComponentID[A](w), ecs.ComponentID[B](w), ecs.ComponentID[C](w), ecs.ComponentID[D](w), ecs.ComponentID[E](w), ecs.ComponentID[F](w), ecs.ComponentID[G](w)},
		world: w,
	}
}

// Get all the Map7's components to the given entity.
//
// See also [ecs.World.Get].
func (m *Map7[A, B, C, D, E, F, G]) Get(entity ecs.Entity) (*A, *B, *C, *D, *E, *F, *G) {
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4])), (*F)(m.world.Get(entity, m.ids[5])), (*G)(m.world.Get(entity, m.ids[6]))
}

//////////////////////////////////////////////////////////////////////////

// Map8 is a helper for mapping eight components.
type Map8[A any, B any, C any, D any, E any, F any, G any, H any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMap8 creates a new Map8 object.
func NewMap8[A any, B any, C any, D any, E any, F any, G any, H any](w *ecs.World) Map8[A, B, C, D, E, F, G, H] {
	return Map8[A, B, C, D, E, F, G, H]{
		ids:   []ecs.ID{ecs.ComponentID[A](w), ecs.ComponentID[B](w), ecs.ComponentID[C](w), ecs.ComponentID[D](w), ecs.ComponentID[E](w), ecs.ComponentID[F](w), ecs.ComponentID[G](w), ecs.ComponentID[H](w)},
		world: w,
	}
}

// Get all the Map8's components to the given entity.
//
// See also [ecs.World.Get].
func (m *Map8[A, B, C, D, E, F, G, H]) Get(entity ecs.Entity) (*A, *B, *C, *D, *E, *F, *G, *H) {
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4])), (*F)(m.world.Get(entity, m.ids[5])), (*G)(m.world.Get(entity, m.ids[6])), (*H)(m.world.Get(entity, m.ids[7]))
}
