package generic

// Code generated by go generate; DO NOT EDIT.

import (
	"github.com/mlange-42/arche/ecs"
)

//////////////////////////////////////////////////////////////////////////

// Mutate1 mutates 1 components
type Mutate1[A any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMutate1 creates a new Mutate1
func NewMutate1[A any](w *ecs.World) Mutate1[A] {
	return Mutate1[A]{
		ids:   []ecs.ID{ecs.ComponentID[A](w)},
		world: w,
	}
}

func (m *Mutate1[A]) NewEntity() (ecs.Entity, *A) {
	entity := m.world.NewEntity(m.ids...)
	return entity, (*A)(m.world.Get(entity, m.ids[0]))
}

func (m *Mutate1[A]) NewEntityWith(a *A) (ecs.Entity, *A) {
	entity := m.world.NewEntityWith(
		ecs.Component{ID: m.ids[0], Component: a},
	)
	return entity, (*A)(m.world.Get(entity, m.ids[0]))
}

func (m *Mutate1[A]) Add(entity ecs.Entity) *A {
	m.world.Add(entity, m.ids...)
	return (*A)(m.world.Get(entity, m.ids[0]))
}

func (m *Mutate1[A]) Assign(entity ecs.Entity, a *A) *A {
	m.world.AssignN(entity,
		ecs.Component{ID: m.ids[0], Component: a},
	)
	return (*A)(m.world.Get(entity, m.ids[0]))
}

func (m *Mutate1[A]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}

//////////////////////////////////////////////////////////////////////////

// Mutate2 mutates 2 components
type Mutate2[A any, B any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMutate2 creates a new Mutate2
func NewMutate2[A any, B any](w *ecs.World) Mutate2[A, B] {
	return Mutate2[A, B]{
		ids:   []ecs.ID{ecs.ComponentID[A](w), ecs.ComponentID[B](w)},
		world: w,
	}
}

func (m *Mutate2[A, B]) NewEntity() (ecs.Entity, *A, *B) {
	entity := m.world.NewEntity(m.ids...)
	return entity, (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1]))
}

func (m *Mutate2[A, B]) NewEntityWith(a *A, b *B) (ecs.Entity, *A, *B) {
	entity := m.world.NewEntityWith(
		ecs.Component{ID: m.ids[0], Component: a},
		ecs.Component{ID: m.ids[1], Component: b},
	)
	return entity, (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1]))
}

func (m *Mutate2[A, B]) Add(entity ecs.Entity) (*A, *B) {
	m.world.Add(entity, m.ids...)
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1]))
}

func (m *Mutate2[A, B]) Assign(entity ecs.Entity, a *A, b *B) (*A, *B) {
	m.world.AssignN(entity,
		ecs.Component{ID: m.ids[0], Component: a},
		ecs.Component{ID: m.ids[1], Component: b},
	)
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1]))
}

func (m *Mutate2[A, B]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}

//////////////////////////////////////////////////////////////////////////

// Mutate3 mutates 3 components
type Mutate3[A any, B any, C any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMutate3 creates a new Mutate3
func NewMutate3[A any, B any, C any](w *ecs.World) Mutate3[A, B, C] {
	return Mutate3[A, B, C]{
		ids:   []ecs.ID{ecs.ComponentID[A](w), ecs.ComponentID[B](w), ecs.ComponentID[C](w)},
		world: w,
	}
}

func (m *Mutate3[A, B, C]) NewEntity() (ecs.Entity, *A, *B, *C) {
	entity := m.world.NewEntity(m.ids...)
	return entity, (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2]))
}

func (m *Mutate3[A, B, C]) NewEntityWith(a *A, b *B, c *C) (ecs.Entity, *A, *B, *C) {
	entity := m.world.NewEntityWith(
		ecs.Component{ID: m.ids[0], Component: a},
		ecs.Component{ID: m.ids[1], Component: b},
		ecs.Component{ID: m.ids[2], Component: c},
	)
	return entity, (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2]))
}

func (m *Mutate3[A, B, C]) Add(entity ecs.Entity) (*A, *B, *C) {
	m.world.Add(entity, m.ids...)
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2]))
}

func (m *Mutate3[A, B, C]) Assign(entity ecs.Entity, a *A, b *B, c *C) (*A, *B, *C) {
	m.world.AssignN(entity,
		ecs.Component{ID: m.ids[0], Component: a},
		ecs.Component{ID: m.ids[1], Component: b},
		ecs.Component{ID: m.ids[2], Component: c},
	)
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2]))
}

func (m *Mutate3[A, B, C]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}

//////////////////////////////////////////////////////////////////////////

// Mutate4 mutates 4 components
type Mutate4[A any, B any, C any, D any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMutate4 creates a new Mutate4
func NewMutate4[A any, B any, C any, D any](w *ecs.World) Mutate4[A, B, C, D] {
	return Mutate4[A, B, C, D]{
		ids:   []ecs.ID{ecs.ComponentID[A](w), ecs.ComponentID[B](w), ecs.ComponentID[C](w), ecs.ComponentID[D](w)},
		world: w,
	}
}

func (m *Mutate4[A, B, C, D]) NewEntity() (ecs.Entity, *A, *B, *C, *D) {
	entity := m.world.NewEntity(m.ids...)
	return entity, (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3]))
}

func (m *Mutate4[A, B, C, D]) NewEntityWith(a *A, b *B, c *C, d *D) (ecs.Entity, *A, *B, *C, *D) {
	entity := m.world.NewEntityWith(
		ecs.Component{ID: m.ids[0], Component: a},
		ecs.Component{ID: m.ids[1], Component: b},
		ecs.Component{ID: m.ids[2], Component: c},
		ecs.Component{ID: m.ids[3], Component: d},
	)
	return entity, (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3]))
}

func (m *Mutate4[A, B, C, D]) Add(entity ecs.Entity) (*A, *B, *C, *D) {
	m.world.Add(entity, m.ids...)
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3]))
}

func (m *Mutate4[A, B, C, D]) Assign(entity ecs.Entity, a *A, b *B, c *C, d *D) (*A, *B, *C, *D) {
	m.world.AssignN(entity,
		ecs.Component{ID: m.ids[0], Component: a},
		ecs.Component{ID: m.ids[1], Component: b},
		ecs.Component{ID: m.ids[2], Component: c},
		ecs.Component{ID: m.ids[3], Component: d},
	)
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3]))
}

func (m *Mutate4[A, B, C, D]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}

//////////////////////////////////////////////////////////////////////////

// Mutate5 mutates 5 components
type Mutate5[A any, B any, C any, D any, E any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMutate5 creates a new Mutate5
func NewMutate5[A any, B any, C any, D any, E any](w *ecs.World) Mutate5[A, B, C, D, E] {
	return Mutate5[A, B, C, D, E]{
		ids:   []ecs.ID{ecs.ComponentID[A](w), ecs.ComponentID[B](w), ecs.ComponentID[C](w), ecs.ComponentID[D](w), ecs.ComponentID[E](w)},
		world: w,
	}
}

func (m *Mutate5[A, B, C, D, E]) NewEntity() (ecs.Entity, *A, *B, *C, *D, *E) {
	entity := m.world.NewEntity(m.ids...)
	return entity, (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4]))
}

func (m *Mutate5[A, B, C, D, E]) NewEntityWith(a *A, b *B, c *C, d *D, e *E) (ecs.Entity, *A, *B, *C, *D, *E) {
	entity := m.world.NewEntityWith(
		ecs.Component{ID: m.ids[0], Component: a},
		ecs.Component{ID: m.ids[1], Component: b},
		ecs.Component{ID: m.ids[2], Component: c},
		ecs.Component{ID: m.ids[3], Component: d},
		ecs.Component{ID: m.ids[4], Component: e},
	)
	return entity, (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4]))
}

func (m *Mutate5[A, B, C, D, E]) Add(entity ecs.Entity) (*A, *B, *C, *D, *E) {
	m.world.Add(entity, m.ids...)
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4]))
}

func (m *Mutate5[A, B, C, D, E]) Assign(entity ecs.Entity, a *A, b *B, c *C, d *D, e *E) (*A, *B, *C, *D, *E) {
	m.world.AssignN(entity,
		ecs.Component{ID: m.ids[0], Component: a},
		ecs.Component{ID: m.ids[1], Component: b},
		ecs.Component{ID: m.ids[2], Component: c},
		ecs.Component{ID: m.ids[3], Component: d},
		ecs.Component{ID: m.ids[4], Component: e},
	)
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4]))
}

func (m *Mutate5[A, B, C, D, E]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}

//////////////////////////////////////////////////////////////////////////

// Mutate6 mutates 6 components
type Mutate6[A any, B any, C any, D any, E any, F any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMutate6 creates a new Mutate6
func NewMutate6[A any, B any, C any, D any, E any, F any](w *ecs.World) Mutate6[A, B, C, D, E, F] {
	return Mutate6[A, B, C, D, E, F]{
		ids:   []ecs.ID{ecs.ComponentID[A](w), ecs.ComponentID[B](w), ecs.ComponentID[C](w), ecs.ComponentID[D](w), ecs.ComponentID[E](w), ecs.ComponentID[F](w)},
		world: w,
	}
}

func (m *Mutate6[A, B, C, D, E, F]) NewEntity() (ecs.Entity, *A, *B, *C, *D, *E, *F) {
	entity := m.world.NewEntity(m.ids...)
	return entity, (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4])), (*F)(m.world.Get(entity, m.ids[5]))
}

func (m *Mutate6[A, B, C, D, E, F]) NewEntityWith(a *A, b *B, c *C, d *D, e *E, f *F) (ecs.Entity, *A, *B, *C, *D, *E, *F) {
	entity := m.world.NewEntityWith(
		ecs.Component{ID: m.ids[0], Component: a},
		ecs.Component{ID: m.ids[1], Component: b},
		ecs.Component{ID: m.ids[2], Component: c},
		ecs.Component{ID: m.ids[3], Component: d},
		ecs.Component{ID: m.ids[4], Component: e},
		ecs.Component{ID: m.ids[5], Component: f},
	)
	return entity, (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4])), (*F)(m.world.Get(entity, m.ids[5]))
}

func (m *Mutate6[A, B, C, D, E, F]) Add(entity ecs.Entity) (*A, *B, *C, *D, *E, *F) {
	m.world.Add(entity, m.ids...)
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4])), (*F)(m.world.Get(entity, m.ids[5]))
}

func (m *Mutate6[A, B, C, D, E, F]) Assign(entity ecs.Entity, a *A, b *B, c *C, d *D, e *E, f *F) (*A, *B, *C, *D, *E, *F) {
	m.world.AssignN(entity,
		ecs.Component{ID: m.ids[0], Component: a},
		ecs.Component{ID: m.ids[1], Component: b},
		ecs.Component{ID: m.ids[2], Component: c},
		ecs.Component{ID: m.ids[3], Component: d},
		ecs.Component{ID: m.ids[4], Component: e},
		ecs.Component{ID: m.ids[5], Component: f},
	)
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4])), (*F)(m.world.Get(entity, m.ids[5]))
}

func (m *Mutate6[A, B, C, D, E, F]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}

//////////////////////////////////////////////////////////////////////////

// Mutate7 mutates 7 components
type Mutate7[A any, B any, C any, D any, E any, F any, G any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMutate7 creates a new Mutate7
func NewMutate7[A any, B any, C any, D any, E any, F any, G any](w *ecs.World) Mutate7[A, B, C, D, E, F, G] {
	return Mutate7[A, B, C, D, E, F, G]{
		ids:   []ecs.ID{ecs.ComponentID[A](w), ecs.ComponentID[B](w), ecs.ComponentID[C](w), ecs.ComponentID[D](w), ecs.ComponentID[E](w), ecs.ComponentID[F](w), ecs.ComponentID[G](w)},
		world: w,
	}
}

func (m *Mutate7[A, B, C, D, E, F, G]) NewEntity() (ecs.Entity, *A, *B, *C, *D, *E, *F, *G) {
	entity := m.world.NewEntity(m.ids...)
	return entity, (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4])), (*F)(m.world.Get(entity, m.ids[5])), (*G)(m.world.Get(entity, m.ids[6]))
}

func (m *Mutate7[A, B, C, D, E, F, G]) NewEntityWith(a *A, b *B, c *C, d *D, e *E, f *F, g *G) (ecs.Entity, *A, *B, *C, *D, *E, *F, *G) {
	entity := m.world.NewEntityWith(
		ecs.Component{ID: m.ids[0], Component: a},
		ecs.Component{ID: m.ids[1], Component: b},
		ecs.Component{ID: m.ids[2], Component: c},
		ecs.Component{ID: m.ids[3], Component: d},
		ecs.Component{ID: m.ids[4], Component: e},
		ecs.Component{ID: m.ids[5], Component: f},
		ecs.Component{ID: m.ids[6], Component: g},
	)
	return entity, (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4])), (*F)(m.world.Get(entity, m.ids[5])), (*G)(m.world.Get(entity, m.ids[6]))
}

func (m *Mutate7[A, B, C, D, E, F, G]) Add(entity ecs.Entity) (*A, *B, *C, *D, *E, *F, *G) {
	m.world.Add(entity, m.ids...)
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4])), (*F)(m.world.Get(entity, m.ids[5])), (*G)(m.world.Get(entity, m.ids[6]))
}

func (m *Mutate7[A, B, C, D, E, F, G]) Assign(entity ecs.Entity, a *A, b *B, c *C, d *D, e *E, f *F, g *G) (*A, *B, *C, *D, *E, *F, *G) {
	m.world.AssignN(entity,
		ecs.Component{ID: m.ids[0], Component: a},
		ecs.Component{ID: m.ids[1], Component: b},
		ecs.Component{ID: m.ids[2], Component: c},
		ecs.Component{ID: m.ids[3], Component: d},
		ecs.Component{ID: m.ids[4], Component: e},
		ecs.Component{ID: m.ids[5], Component: f},
		ecs.Component{ID: m.ids[6], Component: g},
	)
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4])), (*F)(m.world.Get(entity, m.ids[5])), (*G)(m.world.Get(entity, m.ids[6]))
}

func (m *Mutate7[A, B, C, D, E, F, G]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}

//////////////////////////////////////////////////////////////////////////

// Mutate8 mutates 8 components
type Mutate8[A any, B any, C any, D any, E any, F any, G any, H any] struct {
	ids   []ecs.ID
	world *ecs.World
}

// NewMutate8 creates a new Mutate8
func NewMutate8[A any, B any, C any, D any, E any, F any, G any, H any](w *ecs.World) Mutate8[A, B, C, D, E, F, G, H] {
	return Mutate8[A, B, C, D, E, F, G, H]{
		ids:   []ecs.ID{ecs.ComponentID[A](w), ecs.ComponentID[B](w), ecs.ComponentID[C](w), ecs.ComponentID[D](w), ecs.ComponentID[E](w), ecs.ComponentID[F](w), ecs.ComponentID[G](w), ecs.ComponentID[H](w)},
		world: w,
	}
}

func (m *Mutate8[A, B, C, D, E, F, G, H]) NewEntity() (ecs.Entity, *A, *B, *C, *D, *E, *F, *G, *H) {
	entity := m.world.NewEntity(m.ids...)
	return entity, (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4])), (*F)(m.world.Get(entity, m.ids[5])), (*G)(m.world.Get(entity, m.ids[6])), (*H)(m.world.Get(entity, m.ids[7]))
}

func (m *Mutate8[A, B, C, D, E, F, G, H]) NewEntityWith(a *A, b *B, c *C, d *D, e *E, f *F, g *G, h *H) (ecs.Entity, *A, *B, *C, *D, *E, *F, *G, *H) {
	entity := m.world.NewEntityWith(
		ecs.Component{ID: m.ids[0], Component: a},
		ecs.Component{ID: m.ids[1], Component: b},
		ecs.Component{ID: m.ids[2], Component: c},
		ecs.Component{ID: m.ids[3], Component: d},
		ecs.Component{ID: m.ids[4], Component: e},
		ecs.Component{ID: m.ids[5], Component: f},
		ecs.Component{ID: m.ids[6], Component: g},
		ecs.Component{ID: m.ids[7], Component: h},
	)
	return entity, (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4])), (*F)(m.world.Get(entity, m.ids[5])), (*G)(m.world.Get(entity, m.ids[6])), (*H)(m.world.Get(entity, m.ids[7]))
}

func (m *Mutate8[A, B, C, D, E, F, G, H]) Add(entity ecs.Entity) (*A, *B, *C, *D, *E, *F, *G, *H) {
	m.world.Add(entity, m.ids...)
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4])), (*F)(m.world.Get(entity, m.ids[5])), (*G)(m.world.Get(entity, m.ids[6])), (*H)(m.world.Get(entity, m.ids[7]))
}

func (m *Mutate8[A, B, C, D, E, F, G, H]) Assign(entity ecs.Entity, a *A, b *B, c *C, d *D, e *E, f *F, g *G, h *H) (*A, *B, *C, *D, *E, *F, *G, *H) {
	m.world.AssignN(entity,
		ecs.Component{ID: m.ids[0], Component: a},
		ecs.Component{ID: m.ids[1], Component: b},
		ecs.Component{ID: m.ids[2], Component: c},
		ecs.Component{ID: m.ids[3], Component: d},
		ecs.Component{ID: m.ids[4], Component: e},
		ecs.Component{ID: m.ids[5], Component: f},
		ecs.Component{ID: m.ids[6], Component: g},
		ecs.Component{ID: m.ids[7], Component: h},
	)
	return (*A)(m.world.Get(entity, m.ids[0])), (*B)(m.world.Get(entity, m.ids[1])), (*C)(m.world.Get(entity, m.ids[2])), (*D)(m.world.Get(entity, m.ids[3])), (*E)(m.world.Get(entity, m.ids[4])), (*F)(m.world.Get(entity, m.ids[5])), (*G)(m.world.Get(entity, m.ids[6])), (*H)(m.world.Get(entity, m.ids[7]))
}

func (m *Mutate8[A, B, C, D, E, F, G, H]) Remove(entity ecs.Entity) {
	m.world.Remove(entity, m.ids...)
}
