baseURL = 'https://mlange-42.github.io/arche/'
languageCode = 'en-us'
title = 'Arche'

[module]
[[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

theme = "hugo-theme-relearn"

[outputs]
home = [ "html", "rss", "search"]

[params]
images = [ "images/social.svg" ]
description = "Documentation for Arche, the Go Entity Component System (ECS)"

editURL = "https://github.com/mlange-42/arche/edit/main/docs/content/${FilePath}"

themeVariant = [
	{ identifier = "auto",  name = "Auto", auto = [] },
	{ identifier = "light"  },
	{ identifier = "dark"   },
]

disableLandingPageButton = true
showVisitedLinks = true
collapsibleMenu = true

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/mlange-42/arche"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> API reference"
identifier = "hugodoc"
url = "https://pkg.go.dev/github.com/mlange-42/arche"
weight = 20
