name: Coverage

on: [push]

jobs:

  coverage:
    name: Check test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.x'
      - name: Install dependencies
        run: go get .
      - name: Test
        run: |
          go test -v ./... -covermode=count -coverprofile="coverage.out"
          go tool cover -func="coverage.out" -o="report.out"
          python ./.github/check_coverage.py report.out
