name: Publish

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions: 
  contents: write

jobs:

  build:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.x'
      - name: Install dependencies
        run: go get ./...
      - name: Run doc tests
        run: |
          go test -v ./docs/content/...
      - name: Run benchmark tables
        run: |
          go run ./benchmark/table | tee docs/content/generated/_benchmarks.md
      - name: Copy changelog
        run: |
          cp ./CHANGELOG.md ./docs/content/generated/_changelog.md
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.143.1'
      - name: Build Site
        run: hugo -s docs --noChmod
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: docs/public
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
